### ISSUE TITLE
Extend options to support passthrough

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#1054]
### Description of problem
Today, if a workload does not match any of the options, we explode. We are suggesting that it is possible that a workload purposely does not want to match any of the options and would instead like the ability to move on to the next step. 

### Proposed solution

https://gist.github.com/squeedee/ed833b036ecc8f983d5aaf5801cc5fa8

**Comment by emmjohnson** [comment]
Do we have any thoughts what the shape of `status.resource[x]` should be for the "skipped" resource?

Possibly:
```
    - name: source-tester
      inputs:
        - name: source-provider
       outputs:
        - name: url
          preview: |
           ...
        - name: revision
          preview: |
            ...
```

Leaving out `stampedRef`, `templateRef`, and `conditions`
