### ISSUE TITLE
Allow Pipeline Inputs to be a map or list

### ISSUE THREAD

**Issue by waciumawanjohi** [vmware-tanzu/cartographer#138]
As an operator, I want to have flexibility in how I specify my Pipeline inputs.

Problem:
Inputs is a `map[string]apiextensionsv1.JSON`. It seems sensible that it could be a `apiextensionsv1.JSON`. This would allow users to specify a list object or a map object. But when it is specified as such, our interpolator fails to stamp out objects properly.

```gherkin
Given a pipeline and runTemplate
When the pipeline specifies Inputs as a list of objects and the runTemplate refers to those values
A proper object is created
```

```gherkin
Given a pipeline and runTemplate
When the pipeline specifies Inputs as a map of objects and the runTemplate refers to those values
A proper object is created
```

# Examples
The current `inputs` object in the kuttl test `pipeline-with-inputs` reads:
```yaml
  inputs:
    some-object:
      nested: hi
      still-nested: bye
    some-list:
      - position: one
        val: first
      - position: two
        val: second
    some-int: 3
    some-string: silly
```

The following yaml should also work after the implementation:
```yaml
  inputs:
  - name: some-object
    value:
      nested: hi
      still-nested: bye
  - name: some-list
    value:
      - position: one
        val: first
      - position: two
        val: second
  - name: some-int
    value: 3
  - name: some-string
    value: silly
```

# Notes
## Backwards Compatibility
This change should be backwards compatible. If any of the current tests fail, this story should be discussed again with the team.
