### ISSUE TITLE
Report on outputs of object even if runTemplate has changed object type

### ISSUE THREAD

**Issue by waciumawanjohi** [vmware-tanzu/cartographer#142]
As an operator, I want to get the output of the most recent successful object, even if the object type has changed.

# Problem
The reporting of outputs should get all historical objects that have been stamped out by the pipeline and the runTemplate. Currently, it gets a subset: the subset of objects that are of the same type as the most recently submitted object. E.g. if the pipeline-runTemplate are currently submitting a Tekton PipelineRun, only Tekton PipelineRuns will be considered when reporting outputs. But what if a user has switched to some other object that has the same success criteria? Will the user expect their Pipeline to continue reporting the output of the old objects until the new object is ready?

```gherkin
Given a runTemplate and Pipeline which are successfully stamping objects and reporting outputs
When the runTemplate is changed so that it stamps out a different type of object which takes some time to succeed
Then the Pipeline can still report the output of the previously successful object
```

# Pseudo-Example
```yaml
apiVersion: carto.run/v1alpha1
kind: RunTemplate
metadata:
  name: my-run-template
spec:
  template:
    apiVersion: v1       # <==
    kind: ConfigMap      # <== when these fields change
```
