### ISSUE TITLE
YTT does not resolve template variables used in the supply chain

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#156]
The idiom we established in `workload-provided-params` does not work with ytt.

See: https://github.com/vmware-tanzu/cartographer/blob/5027e6bb30643a84231099b7aeae429f2a2eed62/tests/kuttl/workload-provided-params/01-supply-chain.yaml#L33

This is because these values are resolved recursively in the template stamper, and no such code exists in the ytt stamper.

Failing kuttl: https://github.com/vmware-tanzu/cartographer/tree/156-failing-recursion-ytt

**Comment by squeedee** [comment]
https://vmware.slack.com/archives/C02F48Q6ZGE/p1632505148031100?thread_ts=1632496122.012200&cid=C02F48Q6ZGE

**Comment by idoru** [comment]
Recursive YAML templating may be infeasible if YTT cannot itself emit further directives, which https://github.com/vmware-tanzu/carvel-ytt/issues/63 seems to imply is the case. Just another 2c to add to the case for RFC 10.

**Comment by DanieldeR** [comment]
We're going to review the impacts from Introducing rfc-0010-supply-chains-supply-default-params #77 before addressing this issue.

**Comment by squeedee** [comment]
> Recursive YAML templating may be infeasible if YTT cannot itself emit further directives, which [vmware-tanzu/carvel-ytt#63](https://github.com/vmware-tanzu/carvel-ytt/issues/63) seems to imply is the case. Just another 2c to add to the case for RFC 10.

Just capturing that this is not the proposed solution. The proposal (in the absence of rfc10) is to recursively resolve jsonpath values in the `input.params` context before sending them to the stamper. In this way, they're resolved values that both ytt and template can use. Further, the recursion in the stamper's template implementation is no longer needed.

**Comment by cirocosta** [comment]
a small reproducible:

```yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    foo: bar
spec:
  params:
    - name: workload-foo
      value: "bar"

---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supplychain
spec:
  selector:
    foo: bar
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterTemplate
        name: template
      params:
        - name: foo
          value: $(workload.spec.params[?(@.name=="workload-foo")].value)$

---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: template
spec:
  params:
    - name: foo
      default: "default"
  ytt: |-
    #@ load("@ytt:data","data")
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cm
    data:
      value: #@ data.values.params.foo
```

should produce a configmap with `value: bar`, but actually produces `value: $(workload.spec.params[?(@.name=="workload-foo")].value)$`
