### ISSUE TITLE
Make the name in the sources/configs/image definitions optional

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#171]
### Description of problem

As an operator, if I define a template that consumes a single upstream component (i.e. a single item in `images:`), and I reference that component by its shortcut name (.i.e `image` instead of `images.some-image.image`), then the name in the supply chain definition becomes meaningless.

### Proposed solution

Should we make this field optional?

### Example

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: source-provider
          name: source                       #< =============== make this field optional

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image                         #< =============== make this field optional
```

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: image
spec:
  imagePath: .status.latestImage

  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
    spec:
      tag: #@ data.values.image_prefix + "$(workload.metadata.name)$"
      serviceAccount: service-account
      builder:
        kind: ClusterBuilder
        name: go-builder
      source:
        blob:
          url: $(source.url)$       #< =============== if I use the shortcut, the name above is never used
```

## Additional Context

We always provide a map of all the components that you consume (.i.e. `images.some-name.mage`), so if the name is missing from the supply chain definition, maybe we don't add it to this map?
