### ISSUE TITLE
Rename 'components:' to 'resources:'

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#181]
### Description of problem

We have a 'components:' block in the SupplyChain, which introduces a new concept 'components' that we don't really refer to anywhere else.

### Proposed solution

Let's simplify things and use 'resources:' instead.

### Example

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:                              #<=============== rename to resources
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: source-provider
          name: source

    - name: deployer
      templateRef:
        kind: ClusterTemplate
        name: app-deploy
      images:
        - component: image-builder
          name: image
```
