### ISSUE TITLE
Make RunTemplate cluster scoped

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#197]
### Description of problem

It's often the case that the `RunTemplate` will be installed by the Operator along with the the rest of the templates from the `SupplyChain`. Since `SupplyChain` templates are cluster scoped, they are accessible from anywhere on the cluster. The `RunTemplate` on the other hand is not cluster scoped, so the operator needs to be aware of where it's getting installed, and make sure they reference the correct namespace in the `Pipeline` definition.

```yaml
apiVersion: carto.run/v1alpha1
kind: RunTemplate
metadata:
  name: tekton
  namespace: some-namespace               #<===================== optional however you need to be aware
                                          #                       of where this is getting installed.
spec:
  outputs:
    url: spec.params[?(@.name=="source-url")].value
    revision: spec.params[?(@.name=="source-revision")].value

  template:
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: $(pipeline.metadata.name)$-
    spec:
      pipelineRef:
        name: $(pipeline.spec.inputs.tekton-pipeline-name)$
      params:
      - name: source-url
        value: $(pipeline.spec.inputs.source-url)$
      - name: source-revision
        value: $(pipeline.spec.inputs.source-revision)$
```

```yaml
apiVersion: kontinue.io/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: testing-pipeline
spec:
  urlPath: .status.outputs.url
  revisionPath: .status.outputs.revision

  template:
    apiVersion: kontinue.io/v1alpha1
    kind: Pipeline
    metadata:
      name: $(workload.name)$
    spec:
      runTemplateRef:
        name: tekton
        kind: RunTemplate
        namespace: some-namespace              # <============= required otherwise it looks in the same 
                                               #                namespace as the workload, which might 
                                               #                not be where it actually got installed.
      inputs:
        url: $(sources[0].url)$
        revision: $(sources[0].revision)$
```

### Proposed solution

Replace the `RunTemplate` with a `ClusterRunTemplate` to mirror the behaviour from the `SupplyChain` templates.
