### ISSUE TITLE
Add ytt to ClusterRunTemplate

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#214]
### Description of problem

All our other templates support `ytt`.

### Proposed solution

Add it to `ClusterRunTemplate`.

### Example

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: some-name
spec:
  template:
    ...
  ytt:                            #< ============ add this
```
