### ISSUE TITLE
Delivery config-to-url

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#220]
Per [Delivery RFC](https://github.com/vmware-tanzu/cartographer/blob/main/rfc/rfc-0013-delivery.md)
### Description of problem

As an operator, I want to be able to pull down k8s configuration from a remote repository and apply it to my cluster. I want this behaviour to be modelled in my cluster in a domain specific language (i.e. Delivery, Deliverable, etc).

[config] ========> [kapp]

### Proposed solution

Introduce 
- [x] `Deliverable`, 
- [x] `ClusterDelivery`, 
- [x] `ClusterDeploymentTemplate` as per https://github.com/sclevine/cartographer/blob/patch-1/rfc/rfc-0013-delivery.md

### Example

Deploy Only
In the following simple example, the delivery:

1. Fetches Kubernetes configuration from a git repository
2. Deploys to the cluster using kapp controller

```yaml
apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: my-app
  labels:
    app.tanzu.vmware.com/deliverable-type: web
spec:
  source:
    git:
      url: https://github.com/ekcasey/hello-world-ops
      ref:
        branch: prod
```

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery
spec:
  selector:
    app.tanzu.vmware.com/deliverable-type: web
  resources:
    - name: config-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-repository
    - name: deployer
      templateRef:
        kind: ClusterDeployTemplate
        name: app-deploy
      source:
        resource: config-provider
```

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: source
spec:
  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  template:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: $(deliverable.metadata.name)$
    spec:
      interval: 1m
      url: $(deliverable.spec.source.git.url)$
      ref: $(deliverable.spec.source.git.ref)$
      gitImplementation: libgit2
      ignore: ""
```

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterDeploymentTemplate
metadata:
  name: app-deploy
spec:
  template:
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: $(deliverable.metadata.name)$
    spec:
      serviceAccountName: default
      fetch:
       - http:
          url: $(source.url)$
      template:
        - ytt: {}
      deploy:
        - kapp: {}
```

## Additional Context

The first iteration of Delivery should NOT worry about `ClusterDeploymentValidationTemplate` 
 or the `observedCompletion` in `ClusterDeploymentTemplate` (as per the Delivery RFC). This primary use case does not concern itself with locking and running validations against a deployed environment.

## notes

We can deliver the `Deliverable` CRD first with a merge and then decide if we can parallelize work (especially around the template catalog)
