### ISSUE TITLE
Pipeline service 0.0.6 seeing new pipeline runs with same inputs

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#226]
```
NAMESPACE  NAME                                                       READY  REASON               AGE
default    Workload/tanzu-java-web-app                                True   Ready                19h
default    ├─App/tanzu-java-web-app                                   -                           18h
default    ├─ConfigMap/tanzu-java-web-app                             -                           18h
default    ├─GitRepository/tanzu-java-web-app                         True   GitOperationSucceed  19h
default    ├─Image/tanzu-java-web-app                                 True                        19h
default    │ ├─Build/tanzu-java-web-app-build-1                       -                           19h
default    │ │ └─Pod/tanzu-java-web-app-build-1-build-pod             False  PodCompleted         19h
default    │ └─SourceResolver/tanzu-java-web-app-source               True                        19h
default    ├─Pipeline/tanzu-java-web-app                              True   Ready                19h
default    │ ├─PipelineRun/tanzu-java-web-app-65pm6                   -                           10h
default    │ │ └─TaskRun/tanzu-java-web-app-65pm6-test-hsrcq          -                           10h
default    │ │   └─Pod/tanzu-java-web-app-65pm6-test-hsrcq-pod-cjqm7  False  PodCompleted         10h
default    │ ├─PipelineRun/tanzu-java-web-app-79wt2                   -                           98m
default    │ │ └─TaskRun/tanzu-java-web-app-79wt2-test-ddgsk          -                           98m
default    │ │   └─Pod/tanzu-java-web-app-79wt2-test-ddgsk-pod-pg4pq  False  PodCompleted         98m
default    │ ├─PipelineRun/tanzu-java-web-app-dkv8m                   -                           9h
default    │ │ └─TaskRun/tanzu-java-web-app-dkv8m-test-9l2zx          -                           9h
default    │ │   └─Pod/tanzu-java-web-app-dkv8m-test-9l2zx-pod-49g6r  False  PodCompleted         9h
default    │ └─PipelineRun/tanzu-java-web-app-hhrgr                   -                           19h
default    │   └─TaskRun/tanzu-java-web-app-hhrgr-test-wttx7          -                           19h
default    │     └─Pod/tanzu-java-web-app-hhrgr-test-wttx7-pod-5l666  False  PodCompleted         19h
default    └─PodIntent/tanzu-java-web-app                             True                        18h
```

All of the pipelineruns have same inputs, unsure why they continued to kick off.

**Comment by cirocosta** [comment]
a small reproducible out of 77ee9657b2af7dbb2d68353419f8f246da58ad5b (current `main`):

1. run cartographer

```bash
# doesn't really matter how, but this is _a_ way (`make run` would be fine too)
# 
./hack/setup.sh cluster cartographer
```

2. submit the following pipeline and runtemplate

```yaml
---
apiVersion: carto.run/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  runTemplateRef:
    name: runtemplate
  inputs: {}

---
apiVersion: carto.run/v1alpha1
kind: RunTemplate
metadata:
  name: runtemplate
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      generateName: cm-
    data:
      foo: bar
```

3. observe that we keep getting new configmaps

```bash
k get cm
```
```console
NAME                                                 DATA   AGE
...
cm-2v9bb                                             1      1s
cm-5dtf7                                             1      3s
cm-5kshk                                             1      2s
cm-6bs74                                             1      2s
cm-7lcs4                                             1      3s
cm-7vs54                                             1      3s
cm-92p2j                                             1      2s
cm-b84g4                                             1      1s
cm-csvj9                                             1      3s
cm-fcsmz                                             1      2s
cm-hgxdz                                             1      1s
cm-hql8g                                             1      3s
cm-ks96k                                             1      1s
cm-kz79n                                             1      1s
cm-l9wf9                                             1      1s
cm-lrfhj                                             1      3s
cm-lsnm2                                             1      3s
cm-mfhz2                                             1      3s
cm-nblgg                                             1      3s
cm-nj4vw                                             1      3s
cm-nph9f                                             1      2s
cm-nplz5                                             1      2s
cm-pgndw                                             1      3s
cm-sbfcx                                             1      1s
cm-tjfst                                             1      2s
cm-whdn9                                             1      3s
```

**Comment by idoru** [comment]
@cirocosta correct me if I'm wrong, but isn't this behavior expected with ConfigMaps?

I think in cases where the submitted record is different (e.g. due to `generateName` in this case) then we only compare against the `spec` of objects in the submitted cache, and `spec`less objects will just be assumed to be cache misses

**Comment by idoru** [comment]
We've added more explicit cache logging, will probably put it up for review once we have a chance to verify our logging approach has some informed approach going forward.

With regards to this actual issue, we deployed to kind yesterday. In order to leverage the caching code appropriately, we installed the test CRD `tests/resources/crds/test.run_tests.yaml` and apply the following:

```
---
apiVersion: carto.run/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  runTemplateRef:
    name: runtemplate
  inputs: {}

---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: runtemplate
spec:
  template:
    apiVersion: test.run/v1alpha1
    kind: Test
    metadata:
      generateName: haha-
    spec:
      value:
        answer: polo-is-the-answer
```

In addition to this, we temporarily lowered the cache expiry time to 30 seconds. Over 17 hours we observed no additional stampings.

It's worth noting that restarting the controller will mean the cache is lost, and we did observe the object being restamped if the controller is restarted with something like:
```
kubectl delete pod $(kubectl get pod -n cartographer-system | tail -n +2 | awk '{print $1}') -n cartographer-system
```

@emmjohnson do you think it's likely the cluster you ran on had upgrades, or maybe the pod was simply rescheduled elsewhere?
