### ISSUE TITLE
Template Authors can specify object failed conditions

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#25]
**Problem**:
Issue "If values cannot be found in Templated Objects, workload status should be Unknown" will default workloads to display an `Unknown` condition if a *Template cannot find its object's expected fields. This is because templated objects can take some time to display expected values. But sometimes templated objects will be in a bad state that will not self-fix. In those cases, Cartographer would best report a problem, with a workload ready status `False`. Cartographer must rely on Template Authors to specify indications that an object is in such a bad state.

_"I want to specify indications that a templated object is in a failed state"_

```gherkin
Given a template with badStateConditions
When the templated object matches that condition
Then the workload ComponentsSubmitted and Ready condition are "False"
```

Examples:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: example-build---consume-output-of-components
spec:
  template:
    ...
  waitRules:
    block:
      - path: $(status.conditions[?(@.type=="Succeeded")].status)$
        matcher: True
```

# Notes:
Bad state conditions should have an OR relation. Any one being bad should indicate the object is in a bad state.
