### ISSUE TITLE
Gate resources on condition specified by template author

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#28]
**Customer Request:**
can we express conditions/predicates that apply to the watched resource and act as gates on updating template target resources?

...Having the supply chain be “aware” of specific conditions could also be a first step to UX conveniences around “is my supply chain green or red right now”

_"I want to declare criteria for templated objects to be considered in good state"_

```gherkin
Given a workload, supply chain, template triplet
When the user specifies a positive condition on the template
Then no value from that template is passed along the supply chain until the templated object fulfills that template
```

Examples:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: example-build---consume-output-of-components
spec:
  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    metadata:
      name: ...
    spec:
      ...
  imagePath: $(status.latestImage)$
  waitRules:
    goAhead:
      - path: $(status.conditions[?(@.type=="Succeeded")].status)$
        matcher: True
```

# Notes:
- Good state conditions should be treated with an AND relationship. The object should not be considered in a good state unless all of the conditions are met.
- Due to vmware-tanzu/cartographer-private#95 there will need to be a badStateConditions list. See vmware-tanzu/cartographer-private#97.
