### ISSUE TITLE
Operator sees an error if they fail to specify an existing component

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#3]
Recommend we update https://github.com/vmware-tanzu/cartographer/blob/main/tests/integration/supply_chain_validation_test.go#L18-337 to  include:
* When a component refers to an unspecified component.

# Acceptance 
[TBD]

Flows vmware-tanzu/cartographer-private#118

**Comment by emmjohnson** [comment]
This may or may not be already implemented - check that first

**Comment by cirocosta** [comment]
example:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain
spec:
  selector:
    app.tanzu.vmware.com/workload-type: web

  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: source

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: image
      sources:
        - component: whops-i-dont-exist  # !! 
          name: source
```

(^ should & could fail at submission time via our admission webhook but doesn't)
