### ISSUE TITLE
Supply chain should validate it provides expected inputs

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#38]
I want to know about errors in my supply-chain as soon as possible

```gherkin
Given a *Template A which expects N sources/images/opinions
When a supply-chain component points to *Template A and provides fewer than N sources/images/opinions
Then the supply-chain Ready condition is False with reason "ComponentInputsInsufficientForTemplate"
And there is a helpful message
```

Example:

```yaml
apiVersion: kontinue.io/v1alpha1
kind: SupplyChain
spec:
  components:
    ...

    - name: built-image-provider
      templateRef:
        kind: BuildTemplate
        name: kpack-battery
      sources:
        - component: app-provider
          name: app-provider

---

apiVersion: carto.run/v1alpha1
kind: BuildTemplate
metadata:
  name: kpack-battery
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-build
    data:
      favoriteURL: $(sources.0.url)$
      secondFavoriteURL: $(sources.1.url)$
```
results in
```yaml
apiVersion: carto.run/v1alpha1
kind: SupplyChain
status:
  conditions:
    - type: Ready
      status: "False"
      reason: ComponentInputsInsufficientForTemplate
      message: component 'provider' does not provide expected sources[1] # <--- does not need to be exactly this
```

```gherkin
Given a *Template A which expects source/image/opinion by name
When a supply-chain component points to *Template A and provides no source/image/opinion with said name
Then the supply-chain Ready condition is False with reason "ComponentInputsInsufficientForTemplate"
And there is a helpful message
```

Example:

```yaml
apiVersion: carto.run/v1alpha1
kind: SupplyChain
spec:
  components:
    ...

    - name: built-image-provider
      templateRef:
        kind: BuildTemplate
        name: kpack-battery
      sources:
        - component: app-provider
          name: app-provider

---

apiVersion: carto.run/v1alpha1
kind: BuildTemplate
metadata:
  name: kpack-battery
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-build
    data:
      favoriteURL: $(sources[?(@.name==solo-source-provider)].revision)$
```
results in
```yaml
apiVersion: carto.run/v1alpha1
kind: SupplyChain
status:
  conditions:
    - type: Ready
      status: "False"
      reason: ComponentInputsInsufficientForTemplate
      message: component 'provider' does not provide expected source with name solo-source-provider # <--- does not need to be exactly this
```
