### ISSUE TITLE
Component order should not affect stamping of resources

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#40]
**Setup:**
We should think of the supply chain as some
- eventually consistent
- acyclic
- directed
graph with nodes (e.g. templated resources) source(s) (e.g. workload) and sink(s) (e.g. a pod definition from an opinion service).

Let us define a "valid" set of sources as a set that produces a graph where all sinks are resolvable. That is, a valid set of sources will not raise any errors in the nodes of the supply chain graph. Conversely, an "invalid" set will produce an error.

**Problem:**
Currently, it is possible to submit a valid set of sources, followed by an invalid set of sources, and thereby prevent a sink from producing an output. Posit this graph:
A->B->C->D
Assume C takes a significant period of time to resolve.

Valid input to A is given.
This passes to B and C.
While C is working, invalid input to A is given. This causes B to error when it attempts to stamp out a resource.

The Cartographer controller currently will not continue to check the output of C. Until A has another valid input, D will be starved.

This is bad.

_"I want to ensure that components that can be deployed in the graph, are deployed, regardless of the state of other components."_

```gherkin
Given a supply-chain that lists some components that will error before other components that could succeed
When Cartographer controller reconciles
Then the components that could succeed, do succeed.
```

Examples:

```
# Given a supply chain blueprint and templates

apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: git-template
spec:
  urlPath: .data.workload_git_url
  revisionPath: .data.workload_git_url
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-source
    data:
      workload_git_url: $(workload.source.git.url)$

---

apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: git-template-from-params
spec:
  params:
    - name: a-url
      default: git@github.com:kontinue/example-app.git
  urlPath: .value.cat-lives
  revisionPath: .value.critters
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-source-from-params
    data:
      workload_params_url: $(params[0].value)$

---

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops---ordering
spec:
  selector:
    integration-test: "workload-1"
  components:
    - name: source-provider-from-params
      templateRef:
        kind: ClusterSourceTemplate
        name: git-template-from-params
      params:
        - name: a-url
          path: $(workload.params[0].value)$

    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-template

---

# then resources that can be stamped out are created

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-source-from-params
data:
  workload_params_url: original-url

---

# when a workload does not provide all necessary values

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    integration-test: "workload-1"
spec:
  params:
    - name: url
      value: original-url

#  source:              # Missing value
#    git:
#      url: some-url

---

# And when the supply chain changes the order of the components

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops---ordering
spec:
  components:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: git-template

    - name: source-provider-from-params
      templateRef:
        kind: ClusterSourceTemplate
        name: git-template-from-params
      params:
        - name: a-url
          path: $(workload.params[0].value)$

#    - name: source-provider-from-params
#      templateRef:
#        kind: ClusterSourceTemplate
#        name: git-template-from-params
#      params:
#        - name: a-url
#          path: $(workload.params[0].value)$
#
#    - name: source-provider
#      templateRef:
#        kind: ClusterSourceTemplate
#        name: git-template

---

# then the resources that can be stamped out are created

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-source-from-params
data:
#  workload_params_url: original-url
  workload_params_url: new-url

---

# And there is an update to values

apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    integration-test: "workload-1"
spec:
  params:
    - name: url
      value: new-url

```

The test attempts to deploy two components that both depend on the workflow. One component will fail, the other will succeed. Regardless of the supply chain order, we should always see one component successfully updated.
