### ISSUE TITLE
Cartographer does not update templated object if it's status is Unknown

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#42]
I want to be able to associate the input to a resource with the output from a resource.

```gherkin
Given a supply-chain, templates and workloads which have created a set of templated objects.
When a templated object has a Ready condition whose status is not "True" or "False"
Then Cartographer does not update the object with new template inputs.
```

Example:

Given the below state, Cartographer will not update the kpack image, regardless of a new value for `sources.0.url`
```yaml
apiVersion: kpack.io/v1alpha1
kind: Image
status:
  conditions:
  - lastTransitionTime: "2021-03-02T22:38:29Z"
    status: "Unknown"
    type: Ready

---

apiVersion: experimental.carto.run/v1
kind: BuildTemplate
metadata:
  name: kpack-battery
spec:
  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    spec:
      source:
        blob:
          url: $(sources.0.url)$
```

# Questions
## When resource is ready, which input should Cartographer pass?
Scenario: ResourceN's Ready condition status is "Unknown". ResourceN-1 releases 3 outputs in a row: A, B, then C. When ResourceN's Ready condition status is "True", what input should Cartographer pass to ResourceN? A, or C?

Should we allow users to make the choice? [Concourse has the concept of "every" and "latest" for which resource version to use.](https://concourse-ci.org/jobs.html#schema.step.get-step.version) We know that sometimes customers want pipelines that run on every input. The eventual consistency model of k8s means that we're unable to assure that work won't be "dropped on the factory floor" and go missing in between steps when resource N gives multiple outputs between Cartographer's reconciliation loop. But we can make a best-faith effort of fulfilling such a user choice.

If we allow users to make this choice, it would become a field on the supply-chain.

_My (Waciuma) recommendation is that we start with only the default option of using the latest version of the input resources_

## What to do when resource hangs?
Scenario: ResourceN's Ready condition status has been "Unknown" for a long time. How can the App Operator get things back in a good state?

## How to behave when Template/SupplyChain/Workload change?
Every templated object is stamped out from a combination of the Template, SupplyChain, Workload, as well as the state of earlier work done. This story specifies that changes in the earlier work will not be reflected in the templated object until the templated object is Ready. What should happen if the Template, SupplyChain, Workload change?

Consider: Workloads are owners of the templated objects. If they are patched, does the child object automatically get deleted?

## How to handle resources that do not define a Ready condition with True/False/Unknown?
Not all resources have a Ready condition. Some options:
1. If there is no Ready condition, Cartographer does not wait to overwrite an object's definition. This means that Cartographer cannot reliably trace work through that resource.
2. Cartographer can allow end-users to input what fields on the object indicate that it has finished processing work. This information would be part of the *Template.
