### ISSUE TITLE
bug: cartographer tries to create when it should update

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#484]
### Bug description:

(more details to follow - need to investigate)

I haven't reproduced this myself yet, but, we've got two reports about it already:

```
  status:
    conditions:
    - lastTransitionTime: "2021-12-06T10:13:13Z"
      message: ""
      reason: Ready
      status: "True"
      type: SupplyChainReady
    - lastTransitionTime: "2021-12-07T16:34:24Z"
      message: 'unable to apply object [apps/sample-rabbitmq-app]: create: gitrepositories.source.toolkit.fluxcd.io
        "sample-rabbitmq-app" already exists'
      reason: TemplateRejectedByAPIServer
      status: "False"
      type: ResourcesSubmitted
    - lastTransitionTime: "2021-12-07T16:34:24Z"
      message: 'unable to apply object [apps/sample-rabbitmq-app]: create: gitrepositories.source.toolkit.fluxcd.io
        "sample-rabbitmq-app" already exists'
      reason: TemplateRejectedByAPIServer
      status: "False"
      type: Ready
```

even though that GitRepository object already existed. something that the reporter noticed was that the UUID that the child reference up was different, which might explain why we see this.

apparently, this happens when Workloads are recreated (

### Steps to reproduce:

Not really sure yet - to be worked on.

I tried forcing an object to _not_ be deleted by placing a dummy finalizer:

```yaml
  apiVersion: carto.run/v1alpha1
  kind: ClusterTemplate
  metadata:
    name: template
  spec:
    template:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: $(workload.metadata.name)$
        finalizers:
          - finalizers.this.that/delete
      data:
        foo: bar


  ---
  apiVersion: carto.run/v1alpha1
  kind: ClusterSupplyChain
  metadata:
    name: supplychain
  spec:
    selector:
      foo: bar
    resources:
      - name: template
        templateRef:
          name: template
          kind: ClusterTemplate

  ---
  apiVersion: carto.run/v1alpha1
  kind: Workload
  metadata:
    name: workload
    labels:
      foo: bar
```

and then recreating the Workload, but wasn't able to reproduce the problem.

### Expected behavior:

`update/patch` rather than `create`. 

### Versions:

0.0.7? I'll try to figure out the exact version soon

**Comment by martyspiewak** [comment]
We were able to reproduce with the following steps:

1. Apply the following supply chain and template:
```
---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: template
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: $(workload.metadata.name)$
      labels: $(workload.metadata.labels)$
    data:
      foo: bar

---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supplychain
spec:
  selector:
    foo: bar
  resources:
    - name: template
      templateRef:
        name: template
        kind: ClusterTemplate
```

2. Apply the following workload:
```
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload
  labels:
    foo: bar
spec: {}
```

3. Modify the workload to add a label:
```
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload
  labels:
    foo: bar
    baz: caz
spec: {}
```

The issue seems to be that when you add a label to the workload and it gets propagated down to the templated resources, Cartographer is no longer able to find the existing resources because we are looking for existing resources that match the labels (see [here](https://github.com/vmware-tanzu/cartographer/blob/a9d8ec0a6bbf67d1496cab7a5a9d47f4a3a7b85a/pkg/repository/repository.go#L181)). Since it does not find an existing resource, Cartographer then tries to create it, causing this error.
