### ISSUE TITLE
Stamped out objects should have "template-name" and "template-kind" labels

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#49]
_"I want to discover created objects through their labels."_

```gherkin
Given a *Template
When an object is created from the object
Then the object has a label whose key "carto.run/template-name" has the value of the template name
And the object has a label whose key "carto.run/template-kind" has the value of the template kind
```

Examples:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: some-git-template
spec:
  urlPath: .data.some-data
  revisionPath: .data.some-data
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-source
    data:
      some-data: the-Data-on-the-enterprise
```
will pair with a workload-supplyChain to create
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-source
  labels:
    ...
    kontinue.io/template-name: some-git-template
    kontinue.io/template-kind: ClusterSourceTemplate
...
```

# Notes:
## Bug
The current implementation adds a label for the template name, but hardcodes the key as `carto.run/cluster-build-template-name`.
## Future work
Once we have non-cluster scoped templates we will need to add `template-namespace`.
