### ISSUE TITLE
Reduce set of roles necessary for running the controller

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#51]
## Reduce set of roles necessary for running

_"I want to run the controller with the minimum set of privileges possible."_

```gherkin
Given that I deployed the controller in a Kubernetes cluster
When it reaches out to `kube-apiserver`
Then it does so using a token with the least amount of privileges for finding out cartographer-specific objects
  And it uses a user provided token for maintaining objects templated out
```

## context

Differently from products like [kpack](https://github.com/pivotal/kpack) that
have a known set of resources to interact with (e.g., `kpack` deals with
`Image`, `Build`, `ClusterBuilder`, etc - a set known in advance), `cartographer`
doesn't - it sure knows about `Workload`, `*Template` and `ClusterSupplyChain`,
but it can't know whether a supplychain will drive the creation of a
`kpack/Image` or a `cartographer/Pipeline` that creates a container image using
something like [tekton's kaniko
task](https://github.com/tektoncd/catalog/tree/f5d44bdb7f365706724a14b1805bd2db787d9e8f/task/kaniko)
as it's up to the user to define those.

```

CLSUTERSUPPLYCHAIN-1

        source-provider <--src-- image-provider
              .                       .
              .                       .
       fluxcd/gitrepoistory      kpack/image
            (1)                       (2)


              ==> a Workload reconciling against it would need to
                  provide to the controller a token that is authzed
                  to CRUD (1) and (2)




CLSUTERSUPPLYCHAIN-2

        source-provider <--src------ image-provider
              .                           .
              .                           .
      mozilla/MercurialRepository   cartographer/Pipeline
             (3)                          (4)


              ==> a Workload reconciling against it would need to
                  provide to the controller a token that is authzed
                  to CRUD (3) and (4)

```

In order for the controller to do anything (like, even figure out if there's a
Workload to reconcile), it must have access to `kube-apiserver`'s endpoints. As
doing so requires credentials (acquired either by interpreting `$KUBECONFIG` or
looking up the token from the serviceaccount token secret mount in the pod),
our current approach is to provide to the controller a token that is bound to
`cluster-admin` (when running in a Pod) or using an admin user when running
locally.

### proposal

I believe that we should make it so that the controller's serviceaccount is
bound to a role that provides the most minimum set of permissions possible

- `rw`: `workload`
- `rw`: `clustersupplychain` statuses 
- `r`: `clustersupplychain`
- `r`: `*template`

in which case, the credentials that would let the controller create component's
objects (like `kpack/Image`) would be provided via
`workload.spec.serviceAccountName`.

for instance, assuming we have the following Workload

```yaml
kind: Workload
metadata: {name: foo, labels: {this: that}}
spec:
  serviceAccountName: default
```

that reconciles against the following `ClusterSupplyChain` and `ClusterConfigTemplate`:

```yaml
kind: ClusterSupplyChain
metadata: {name: supplychain}
spec:
  selector: {this: that}
  components:
    - name: source-provider
      templateRef: {kind: ClusterConfigTemplate, name: source-provider}
---
kind: ClusterConfigTemplate
metadata: {name: source-provider}
spec:
  template:
    kind: ConfigMap
    apiVersion: v1
    metadata: {name: $(worload.name)$}
    data: {foo: bar}
```

that `default` serviceaccount would provide to the `cartographer` controller the
authz to CRUD `ConfigMaps` in the workload's namespace.

This is quite similar to how
[kapp-controller](https://github.com/vmware-tanzu/carvel-kapp-controller) has a
very small permission set for the controller itself, but then it's up to the
user to provide the serviceaccount (via the `App`'s `spec.serviceaccountname`)
that has the ability to deploy all the objects that such `App` is supposed to
deploy (see https://carvel.dev/kapp-controller/docs/latest/security-model/#docs)
