### ISSUE TITLE
Change cluster-supply-chain-name to supply-chain-name

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#52]
_"I want to use simple lables."_

```gherkin
Given a template created object
When an object is created from the object
Then the object has a label whose key is "carto.run/supply-chain-name"
And the object does not have a label whose key is "carto.run/cluster-supply-chain-name"
```

Examples:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap-source
  labels:
    carto.run/supply-chain-name: responsible-ops---templates-refer-to-workload
  ...
...
```

# Notes:
## Future work
Once we have non-cluster scoped supply-chains we will need to add `supply-chain-namespace` and `supply-chain-kind`.
