### ISSUE TITLE
Template authors should be able to use `generateName`

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#53]
_"I want to be able to auto generate names of Cartographer created objects"_

```gherkin
Given a *Template with a value for `spec.template.metadata.generateName`
When an object is created from the template
Then the object is successfully created whose name is the specified prefix and a random string suffix
```

Examples:
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  generateName: kpack-template---workload-supply-chain-hardcoded-templates
spec:
  imagePath: .data.average_color_of_the_universe
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      generateName: build
    data:
      average_color_of_the_universe: "Cosmic latte"
```
will create something like
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: build123-some-random-string-xyz
data:
  average_color_of_the_universe: "Cosmic latte"
```
# Notes:
## Patching
Currently, when applying the template to the cluster, we search for the templated object by name/namespace. (Then if we find it, we update it; otherwise we create it). If the template uses generateName, we will need to search for the object by labels instead of by name.
## Kuttl Tests
By assuring a unique object, we should be able to assert on object creation: https://kuttl.dev/docs/testing/asserts-errors.html#listing-resources-in-the-cluster
We can also create an errors file to assert that the object has not been created with only the prefix. e.g.
```yaml
# 01-errors.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: build
data:
  average_color_of_the_universe: "Cosmic latte"
```
