### ISSUE TITLE
If a *Template is deleted, delete the objects stamped out from that template

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#54]
_"I want auto-garbage collection when I delete *Templates"_

```gherkin
Given a Cartographer workload/supply-chain/*Template that has stamped out an object
When the *Template is deleted
Then the previously created object is deleted
```

Examples:
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: first-template
spec:
  imagePath: .data.average_color_of_the_universe
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: first-build
    data:
      average_color_of_the_universe: "Cosmic latte"

---

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops
spec:
  selector:
    integration-test: "workload-supply-chain-hardcoded-templates"
  components:
    - name: first-image-provider
      templateRef:
        kind: ClusterBuildTemplate
        name: first-template

---

# STAMPED OUT OBJECT
apiVersion: v1
kind: ConfigMap
metadata:
  name: first-build
  labels:
    carto.run/workload-name: petclinic
    carto.run/cluster-supply-chain-name: responsible-ops
    carto.run/component-name: first-image-provider
    carto.run/cluster-build-template-name: first-template
  ownerReferences:
    - apiVersion: carto.run/v1alpha1
      kind: Workload
      ...
data:
  average_color_of_the_universe: "Cosmic latte"

```

when `first-template` is deleted, `first-build` should no longer exist in the cluster.

# Notes
## Which controller?
If the SupplyChain cannot find the template for a component, its Ready condition will be False. This is a viable candidate for where to put the logic for this garbage collection. The logic cannot go into the workload reconciler without a refactor, as the workload will not enter its reconciliation function with a supply-chain that is not Ready.

## Differentiate between an error and an absence.
Controller-Runtime's client differentiates between a general error when trying to find an object and not finding the object. In the latter case, the error returned is `k8s.io/apimachinery/pkg/api/errors` `IsNotFound`
https://github.com/kubernetes-sigs/controller-runtime/blob/7d83250a445f2b5371e39e4197d3d0024f95fbdc/pkg/cache/internal/cache_reader.go#L52-L71

https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors#IsNotFound
