### ISSUE TITLE
When updating templated objects with hardcoded names, ensure proper ownership

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#55]
_"I don't want to overwrite objects created by other Cartographer processes"_

```gherkin
Given an object created by a workload/supply-chain/component
When a different workload/supply-chain/component attempts to patch that object
Then the patch fails
And the workload `ComponentsSubmitted` status is False
```

Examples:

```yaml
---
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: MyCanonicalSourceTemplate
spec:
  urlPath: .value.my-number
  revisionPath: .value.my-number
  template:
    apiVersion: carto.run/v1alpha1
    kind: Deliverable
    metadata:
      name: hard-coded-name
    value:
      my-number: 1

---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain-1
spec:
  selector:
    some-key: "some-value"
  components:
    - name: source-provider-first
      templateRef:
        kind: ClusterSourceTemplate
        name: MyCanonicalSourceTemplate
    - name: source-provider-second
      templateRef:
        kind: ClusterSourceTemplate
        name: MyCanonicalSourceTemplate
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload1
  labels:
    some-key: "some-value"
spec:
  params:
    - name: a-number
      value: 1
```
will result in the following Workload status
```
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload1
status:
  conditions:
    - type: SupplyChainReady
      status: "True"
      reason: Ready
    - type: ComponentsSubmitted
      status: "False"
      reason: ObjectOwnedByDifferentComponent
      message: Component source-provider-second may not overwrite the object owned by {workload: {name: workload1, namespace: <some-namespace>}, supply-chain: {name: MyCanonicalSourceTemplate}, component: {name: source-provider-first}}
    - type: Ready
      status: "False"
      reason: ComponentsSubmitted
...
```

# Pre-IPM:
Validate the Reason and Message expected
