### ISSUE TITLE
If a supply-chain is deleted, delete the objects created by that supply-chain

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#56]
_"I want auto-garbage collection when I delete supply-chains"_

```gherkin
Given a Cartographer workload/supply-chain that has stamped out objects
When a supply-chain is deleted
Then the previously created objects are deleted
```

Examples:
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops
spec:
  selector:
    integration-test: "workload-supply-chain-hardcoded-templates"
  components:
    - name: first-image-provider
      templateRef:
        kind: ClusterBuildTemplate
        name: first-template
    - name: second-image-provider
      templateRef:
        kind: ClusterBuildTemplate
        name: second-template

---

# SOME STAMPED OUT OBJECTS
```

When ClusterSupplyChain `responsible-ops` is deleted, the stamped out objects are deleted.

# Notes:
A likely place to insert this logic is in the supply-chain reconciler here:
https://github.com/vmware-tanzu/cartographer/blob/main/pkg/controller/supplychain/reconciler.go
