### ISSUE TITLE
Cartographer rejects *Templates that attempt to set the namespace of the templated objects

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#57]
_"I want to protect users from dangerous practices"_

```gherkin
Given a cluster with Cartographer
When a *Template that defines `spec.template.metadata.namespace` is submitted
Then the template is rejected
```

Examples:
This template would be rejected
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: kpack-template
spec:
  imagePath: .data.average_color_of_the_universe
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-build
      namespace: default # <--- the offending line
    data:
      average_color_of_the_universe: "Cosmic latte"

```
