### ISSUE TITLE
Provide multiple templates for a particular resource in my blueprint

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#573]
### Description of problem

As a supply chain author, I want to provide multiple templates for a particular resource in my blueprint, where each option is selected based on certain characteristics of my resource owner.

### Proposed solution

Implement template `options` as per [RFC 9](https://github.com/vmware-tanzu/cartographer/pull/75)

### Example

```yaml
apiVersion: kontinue.io/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops
spec:
  selector:
    app: web
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        options:                                  # <--- a list
        - name: git-template
          selector:
            matchFields:
              - key: workload.spec.source.git       # <--- path to field in workload spec
                operator: Exists
        - name: imgpkg-bundle-template
          selector:
            matchFields:
              - key: workload.spec.source.image       # <--- path to field in workload spec
                operator: Exists
```

### Acceptance Criteria

- when exactly one of the selectors matches...then happy path
- when more than one of the selectors matches ...  then things go boom ... with useful message of [....] visible on workload status
- when none of the selectors matches....then things go boom ... with useful message of [....] visible on workload status

- when writing a supply chain that uses conditional options and something is written wrong then......
- ...the criteria is identical
- ...the criteria is a subset
- ....the criteria points to keys that don't exist in spec
- ...the operator is invalid
- ...the yaml is malformed
- ....given an operator type. the appropriate values are not included
- ....options is an empty list
-
