### ISSUE TITLE
If component's object changes, delete earlier object

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#58]
_"I want auto-garbage collection when I update supply-chain components"_

```gherkin
Given a cartographer workload/supply-chain that has stamped out objects
When a supply-chain's existing component is altered to create a different object
Then the previously created object is deleted
```

Examples:

Initial State
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: original-template
spec:
  imagePath: .data.average_color_of_the_universe
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: original-build
    data:
      average_color_of_the_universe: "Cosmic latte"

---

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops---workload-supply-chain-hardcoded-templates
spec:
  selector:
    integration-test: "workload-supply-chain-hardcoded-templates"
  components:
    - name: image-provider
      templateRef:
        kind: ClusterBuildTemplate
        name: original-template

---

# STAMPED OUT OBJECT
apiVersion: v1
kind: ConfigMap
metadata:
  name: original-build
  labels:
    carto.sh/workload-name: petclinic
    carto.sh/cluster-supply-chain-name: responsible-ops---workload-supply-chain-hardcoded-templates
    carto.sh/component-name: image-provider
    carto.sh/cluster-build-template-name: original-template
  ownerReferences:
    - apiVersion: carto.sh/v1alpha1
      kind: Workload
      ...
data:
  average_color_of_the_universe: "Cosmic latte"
```

when the supply-chain is updated to

```yaml
apiVersion: carto.sh/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: responsible-ops---workload-supply-chain-hardcoded-templates
spec:
  selector:
    integration-test: "workload-supply-chain-hardcoded-templates"
  components:
    - name: image-provider
      templateRef:
        kind: ClusterBuildTemplate
        name: replacement-template

---

apiVersion: carto.sh/v1alpha1
kind: ClusterBuildTemplate
metadata:
  name: replacement-template
spec:
  imagePath: .data.best_litigant_against_board
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: test-configmap-opinion
    data:
      best_litigant_against_board: "Brown"
```

then `original-build` should no longer exist in the cluster.

# Notes:
This story also covers the case where the component points to the same *Template, but the *Template has been changed so that it stamps out an object with a different name/kind.
