### ISSUE TITLE
ClusterRunTemplate stamping pod or config map will continuously create new ones

### ISSUE THREAD

**Issue by martyspiewak** [vmware-tanzu/cartographer#587]
### Bug description:
If you have a cluster run template that stamps out a pod or a config map, when you apply a runnable it will continuously stamp out new pods or config maps and garbage collection will not clean anything up.

Outputs are also never added to the runnable status

This seems to be because:
1. we always get a cache miss because we compare specs between the cache and the apiServer and there is no spec on a config map, and the pod's spec gets mutated (at least with the `nodeName`, but possibly with more). Therefore we will always get a cache miss and create a new object.
2. garbage collection is looking for `status.conditions[?(@.type=="Succeeded")].status` ([here](https://github.com/vmware-tanzu/cartographer/blob/29fcadaa57dc7deb25a878abc4a4ff707374bf12/pkg/realizer/runnable/gc/gc.go#L42)) which does not exist on either object. Therefore, it will not clean anything up.

### Steps to reproduce:
Please provide a set of steps to reproduce the behavior (example):
1. Apply attached run template and runnable:
```
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: test-template
spec:
  outputs:
    url: .status.hostIP
  template:
    apiVersion: v1
    kind: Pod
    metadata:
      generateName: test-
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: webserver
```
```
apiVersion: carto.run/v1alpha1
kind: Runnable
metadata:
  name: test
spec:
  runTemplateRef:
    name: test-template
```
2. Observe the pods created in the namespace

### Expected behavior:
One pod should be created and there should be outputs on the runnable.

### Actual behavior:
Pods are continuously created and not cleaned up and there are no outputs.

### Versions:
 - Infrastructure: kind
 - cartographer version: running off main (currently [this commit](https://github.com/vmware-tanzu/cartographer/commit/ddf2477d50c40d8c7a8b39a1a48ac2c7f6616fc8))
 - k8s version: 1.21
