### ISSUE TITLE
Stamped resources should not be allowed to specify a namespace

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#614]
### Bug description:

When specifying a resource to be stamped using ytt, a user is able to specify a destination namespace.

### Steps to reproduce:

1. Write any template using ytt
2. Specify a namespace for the stamped object `namespace-a`
3. Create a workload in `namespace-b`
4. Notice that the stamped object is indeed placed in `namespace-a`

### Expected behavior:

All stamped objects are placed in the same namespace as the workload.

### Actual behavior:

Stamped objects can be placed in any namespace.

### Additional Context

Stamping using conventional templating works as expected.

**Comment by waciumawanjohi** [comment]
Looks like we just need to take this line out of the `if` block:
https://github.com/vmware-tanzu/cartographer/blob/89a5a071f98afc98494a5e1d99043ff5c810dfe4/pkg/templates/stamper.go#L153

**Comment by scothis** [comment]
This would also seem to imply that Cartographer should not stamp cluster scoped resources as well. Having all child resources in the same namespace has an advantage as k8s gc can be used to clean up resource upon workload delete, so long as they have an owner reference

**Comment by emmjohnson** [comment]
We tried to apply - 
```
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: example-first---consume-output-of-resources
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: example-first-configmap
      namespace: some-namespace
    data:
      player_initial_lives: "three"
      player_loves: "gaming"
  urlPath: data.player_initial_lives
  revisionPath: data.player_loves
```

And we get the message from the webhook - 
```
admission webhook "source-template-validator.cartographer.com" denied the request: invalid template: template should not set metadata.namespace on the child object
```

I can see how if you were using ytt you could get pass this.
