### ISSUE TITLE
Remove workload/delivery prefix from template options context

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#668]
### Description of problem

Originally the workload prefix was included to leave room for other prefixes (such as params). However based on the direction from the [matchParams RFC](https://github.com/vmware-tanzu/cartographer/pull/618) this no longer makes sense.

### Proposed solution

Remove `workload`/`delivery` prefix as per [this RFC](https://github.com/vmware-tanzu/cartographer/pull/653)

### Example

```yaml
  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        options: 
        - name: git-template
          selector:
            matchFields:
              - key: workload.spec.source.git       #< ========== remove this 'workload' prefix
                operator: Exists
```
