### ISSUE TITLE
Invalid Selectors should cause validation to fail

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer#687]
When I use an invalid selector then the supply chain should be `Ready:False`

Invalid selectors include (but are not limited to)

```yaml
selectors:
  "-not-": "-valid-"
selectorMatchExpressions:
  - {key: "-invalid", operator: "NOTValid" } 
selectorMatchFields:
  - {key: "not-a-legal-path", operator: "NOTValid" } 
```

### Expected behavior:

```yaml
status: 
  type: Ready
  ready: False
  reason: "invalid selector ...."
```

### Actual behavior:
```yaml
status: 
  type: Ready
  ready: True
  reason: ""
```
