### ISSUE TITLE
I want to identify what version of cartographer is running on cluster

### ISSUE THREAD

**Issue by emmjohnson** [vmware-tanzu/cartographer#707]
### Description of problem

No way to know what version of cartographer is running on the cluster.

### Proposed solution

Have a version file that is updated
Add version to logging
Add version command to main
Package version file in the image

### Example

<Code snippets that illustrate the when/then blocks>

## Additional Context

<Additional notes>

**Comment by cirocosta** [comment]
from slack:

- we could make use of the recommended `app.kubernetes.io/version` label (see [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/))

e.g., tekton controller's labels:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: v0.33.2
    pipeline.tekton.dev/release: v0.33.2
    version: v0.33.2
```

@squeedee gave the suggestion of also including the commit sha as a build id

- (@squeedee) we should probably also include to the linker flags (I'm quite sure that's something `ko` wouldn't block us from) to add the version to the binary itself so we get to log the version (either once or all the time)


but note that we’d then need to change our build process a bit so we could inject the version via linker flags and pass some values via ytt do the objects, so no more draft on every commit I think
