### ISSUE TITLE
R4RFC: Workload spec update for maven artifacts

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#741]
### Description of problem

Currently the [workload spec](https://cartographer.sh/docs/v0.2.0/reference/workload/) has fields for `source.git` and `source.image`, neither of which is suitable for basing a workload off a maven artifact. We are requesting an RFC that proposes an update to the workload spec to address this use case.

### Open question

What about S3 artifacts ([fluxcd Bucket resource](https://fluxcd.io/docs/components/source/buckets/))? Would we treat these the same as maven artifacts?

**Comment by scothis** [comment]
@jwntrs can you add "Maven" to the subject to clarify this isn't related to artifact tracing

**Comment by cirocosta** [comment]
related: https://github.com/nulldriver/maven-resource (concourse)

```yaml
resource_types:
- name: maven-resource
  type: registry-image
  source:
    repository: nulldriver/maven-resource
    tag: latest

resources:
- name: artifact
  type: maven-resource
  source:
    url: https://myrepo.example.com/repository/maven-releases/
    snapshot_url: https://myrepo.example.com/repository/maven-snapshots/
    artifact: com.example:example-webapp:jar
    username: myuser
    password: mypass
    repository_cert: |
      -----BEGIN CERTIFICATE-----
      MIIEowIBAAKCAQEAtCS10/f7W7lkQaSgD/mVeaSOvSF9ql4hf/zfMwfVGgHWjj+W
      <Lots more text>
      DWiJL+OFeg9kawcUL6hQ8JeXPhlImG6RTUffma9+iGQyyBMCGd1l
      -----END CERTIFICATE-----
```
