### ISSUE TITLE
selector with matchFields DoesNotExist does not match

### ISSUE THREAD

**Issue by martyspiewak** [vmware-tanzu/cartographer#802]
### Bug description:
When using the matchFields selector with the `DoesNotExist` operator, the option does not match when the json path does not exist.

### Steps to reproduce:
Please provide a set of steps to reproduce the behavior (example):
1. Apply this supply chain (with some ClusterTemplates `first` and `second`):
```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: test
selector:
  test: true
resources:
  - name: first
     templateRef:
       kind: ClusterTemplate
       options:
         - name: first
            selector:
              matchFields:
                - key: .spec.params[?(@.name=="non-existent")]
                  operator: DoesNotExist
         - name: second
            selector:
              matchFields:
                - key: .spec.params[?(@.name=="non-existent")]
                  operator: Exists
```
2. Apply this workload:
```yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: test
labels:
  test: true
spec:
  params:
    - name: some-param
      value: true
```
3. Observe status of Workload

### Expected behavior:
The first template should match.

### Actual behavior:
The status reports an error that 0 templates matched.
