### ISSUE TITLE
R4RFC: Service claims for non-runtime resources

### ISSUE THREAD

**Issue by jwntrs** [vmware-tanzu/cartographer#825]
### Description of problem

Currently the workload contains top level service claims that are meant to be exposed to runtime resources. There is currently no mechanism to define service claims that are targeted to other resources in the cluster (e.g. build).

### Proposed solution

Requesting an RFC that outlines a solution for how we could introduce service claims to be consumed by other resources.

**Comment by jwntrs** [comment]
@squeedee at some point proposed tagging service claims so that templates could consume only the services tagged for a given resource.

**Comment by cirocosta** [comment]
example use of servicebindings at build time:

```yaml
apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: sample-binding-with-secret
spec:
  tag: my-registry.com/repo
  builder:
    kind: ClusterBuilder
    name: default
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: 0eccc6c2f01d9f055087ebbf03526ed0623e014a
  build:
    services:
    - name: settings-xml
      kind: Secret
      apiVersion: v1
---
apiVersion: v1
kind: Secret
metadata:
  name: settings-xml
type: service.binding/maven
stringData:
  type: maven
  provider: sample
  settings.xml: <settings>...</settings>
```

_(see [`kpack/service-bindings.md`](https://github.com/pivotal/kpack/blob/eb84c15f51b3d95fffe982679028471881d4f35c/docs/servicebindings.md#sample-maven-app-image-with-a-settingsxml-service-binding))_

**Comment by squeedee** [comment]
Won't implement (at this time)

Working with kpack is the common pain point, passing a secret to it's `services` key. These aren't really services, and can be implemented by using params (which also provide per-supply-chain fallbacks), eg:

```
spec:
  params:
    - name: build-secrets
      value: 
        - name: settings-xml
          kind: Secret
          apiVersion: v1
```

This avoids spec changes to the Cartographer API.

The one concern is providing these definitions with the CLI, however this is mitigated by this [CLI issue](https://github.com/vmware-tanzu/apps-cli-plugin/issues/103)
