### ISSUE TITLE
realizer stamps out objects even though their dependencies haven't been met yet

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#907]
### Bug description:

Despite a dependency in the graph not being met, objects are stamped out and submitted to kubernetes.
This can be innocuous some times, but not always - e.g., without the dependencies being met, the objects get stamped out with empty values for places where, e.g.,  `#@ data.values.source.url` or `$(source.url)$` would be interpolated.

### Steps to reproduce:

1. create a blueprint (supplychain in the example below) that has 2+ resources with a dependency between them

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: test
spec:
  selector:
    foo: bar
  resources:
    - name: first
      templateRef:
        kind: ClusterSourceTemplate
        name: template
      params:
        - name: name
          value: first

    - name: second
      templateRef:
        kind: ClusterSourceTemplate
        name: template
      params:
        - name: name
          value: second
      sources:
        - resource: first
          name: source
```

2. create the templates in a way that the outputs will never be resolved

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: template
spec:
  params:
    - name: name
      default: "foo"

  urlPath: .data.url                    # this will never be satisfied
  revisionPath: .data.revision   # this will never be satisfied

  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: $(params.name)$
    data: {}
```

3. create a workload and observe that regardless of the inability of the output being provided from `first` to `second`, `second`'s object is stamped out anyway

```yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload
  labels:
    foo: bar
spec: {}
```

```console
$ k tree workload workload
NAMESPACE  NAME                READY    REASON              AGE
default    Workload/workload   Unknown  MissingValueAtPath  4m47s
default    ├─ConfigMap/first   -                            4m7s
default    └─ConfigMap/second  -                            4m7s
```

### Expected behavior:

Have the resource that depends on another only stamped out if its dependency is met (i.e., the output it needs is provided).

### Logs, k8s object dumps:

```yaml
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workload
  namespace: default
spec: {}
status:
  conditions:
  - lastTransitionTime: "2022-06-22T20:30:42Z"
    message: ""
    reason: Ready
    status: "True"
    type: SupplyChainReady
  - lastTransitionTime: "2022-06-22T20:30:43Z"
    message: waiting to read value [.data.url] from resource [configmap/first] in
      namespace [default]
    reason: MissingValueAtPath
    status: Unknown
    type: ResourcesSubmitted
  - lastTransitionTime: "2022-06-22T20:30:43Z"
    message: ""
    reason: HealthyConditionRule
    status: Unknown
    type: ResourcesHealthy
  - lastTransitionTime: "2022-06-22T20:30:43Z"
    message: waiting to read value [.data.url] from resource [configmap/first] in
      namespace [default]
    reason: MissingValueAtPath
    status: Unknown
    type: Ready
  observedGeneration: 1
  resources:
  - conditions:
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: waiting to read value [.data.url] from resource [configmap/first] in
        namespace [default]
      reason: MissingValueAtPath
      status: Unknown
      type: ResourceSubmitted
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: ""
      reason: OutputNotAvailable
      status: Unknown
      type: Healthy
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: waiting to read value [.data.url] from resource [configmap/first] in
        namespace [default]
      reason: MissingValueAtPath
      status: Unknown
      type: Ready
    name: first
    stampedRef:
      apiVersion: v1
      kind: ConfigMap
      name: first
      namespace: default
    templateRef:
      apiVersion: carto.run/v1alpha1
      kind: ClusterSourceTemplate
      name: template
  - conditions:
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: waiting to read value [.data.url] from resource [configmap/second]
        in namespace [default]
      reason: MissingValueAtPath
      status: Unknown
      type: ResourceSubmitted
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: ""
      reason: OutputNotAvailable
      status: Unknown
      type: Healthy
    - lastTransitionTime: "2022-06-22T20:30:43Z"
      message: waiting to read value [.data.url] from resource [configmap/second]
        in namespace [default]
      reason: MissingValueAtPath
      status: Unknown
      type: Ready
    inputs:
    - name: first
    name: second
    stampedRef:
      apiVersion: v1
      kind: ConfigMap
      name: second
      namespace: default
    templateRef:
      apiVersion: carto.run/v1alpha1
      kind: ClusterSourceTemplate
      name: template
  supplyChainRef:
    kind: ClusterSupplyChain
    name: test
```

<details>
<summary>click to see 20 lines of logs from the controller</summary>
<pre>
{
  "level": "info",
  "ts": 1655929843.3894002,
  "msg": "started",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": {
    "name": "workload",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad"
}
{
  "level": "info",
  "ts": 1655929844.5964944,
  "logger": "workload-stamping-repo-cache",
  "msg": "checking for changes since cached",
  "key": "default:ConfigMap:first"
}
{
  "level": "info",
  "ts": 1655929844.596558,
  "logger": "workload-stamping-repo-cache",
  "msg": "no changes since last submission, checking existing objects on apiserver",
  "key": "default:ConfigMap:first"
}
{
  "level": "info",
  "ts": 1655929844.596564,
  "logger": "workload-stamping-repo-cache",
  "msg": "considering object",
  "key": "default:ConfigMap:first",
  "existingName": "first"
}
{
  "level": "info",
  "ts": 1655929844.5965688,
  "logger": "workload-stamping-repo-cache",
  "msg": "object on apiserver has no spec",
  "key": "default:ConfigMap:first"
}
{
  "level": "info",
  "ts": 1655929844.5965722,
  "msg": "patching object",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "first",
  "template": {
    "kind": "ClusterSourceTemplate",
    "name": "template"
  },
  "object": {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "namespace": "default",
    "name": "first"
  }
}
{
  "level": "error",
  "ts": 1655929844.600686,
  "msg": "failed to retrieve output from object",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "first",
  "template": {
    "kind": "ClusterSourceTemplate",
    "name": "template"
  },
  "object": {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "namespace": "default",
    "name": "first"
  },
  "error": "failed to evaluate json path '.data.url': failed to evaluate the url path [.data.url]: jsonpath returned empty list: .data.url",
  "stacktrace": "github.com/vmware-tanzu/cartographer/pkg/realizer.(*realizer).Realize\n\tgithub.com/vmware-tanzu/cartographer/pkg/realizer/realizer.go:104\ngithub.com/vmware-tanzu/cartographer/pkg/controllers.(*WorkloadReconciler).Reconcile\n\tgithub.com/vmware-tanzu/cartographer/pkg/controllers/workload_reconciler.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"
}
{
  "level": "error",
  "ts": 1655929844.6007662,
  "msg": "failed to realize resource",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "first",
  "error": "unable to retrieve outputs [.data.url] from stamped object [default/first] of type [configmap] for resource [first] in supply chain [test]: failed to evaluate json path '.data.url': failed to evaluate the url path [.data.url]: jsonpath returned empty list: .data.url",
  "stacktrace": "github.com/vmware-tanzu/cartographer/pkg/controllers.(*WorkloadReconciler).Reconcile\n\tgithub.com/vmware-tanzu/cartographer/pkg/controllers/workload_reconciler.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"
}
{
  "level": "info",
  "ts": 1655929844.602902,
  "logger": "workload-stamping-repo-cache",
  "msg": "checking for changes since cached",
  "key": "default:ConfigMap:second"
}
{
  "level": "info",
  "ts": 1655929844.6066983,
  "logger": "workload-stamping-repo-cache",
  "msg": "no changes since last submission, checking existing objects on apiserver",
  "key": "default:ConfigMap:second"
}
{
  "level": "info",
  "ts": 1655929844.6067464,
  "logger": "workload-stamping-repo-cache",
  "msg": "considering object",
  "key": "default:ConfigMap:second",
  "existingName": "second"
}
{
  "level": "info",
  "ts": 1655929844.606753,
  "logger": "workload-stamping-repo-cache",
  "msg": "object on apiserver has no spec",
  "key": "default:ConfigMap:second"
}
{
  "level": "info",
  "ts": 1655929844.6067572,
  "msg": "patching object",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "second",
  "template": {
    "kind": "ClusterSourceTemplate",
    "name": "template"
  },
  "object": {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "namespace": "default",
    "name": "second"
  }
}
{
  "level": "error",
  "ts": 1655929844.6106887,
  "msg": "failed to retrieve output from object",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "second",
  "template": {
    "kind": "ClusterSourceTemplate",
    "name": "template"
  },
  "object": {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "namespace": "default",
    "name": "second"
  },
  "error": "failed to evaluate json path '.data.url': failed to evaluate the url path [.data.url]: jsonpath returned empty list: .data.url",
  "stacktrace": "github.com/vmware-tanzu/cartographer/pkg/realizer.(*realizer).Realize\n\tgithub.com/vmware-tanzu/cartographer/pkg/realizer/realizer.go:104\ngithub.com/vmware-tanzu/cartographer/pkg/controllers.(*WorkloadReconciler).Reconcile\n\tgithub.com/vmware-tanzu/cartographer/pkg/controllers/workload_reconciler.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"
}
{
  "level": "error",
  "ts": 1655929844.6109161,
  "msg": "failed to realize resource",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "resource": "second",
  "error": "unable to retrieve outputs [.data.url] from stamped object [default/second] of type [configmap] for resource [second] in supply chain [test]: failed to evaluate json path '.data.url': failed to evaluate the url path [.data.url]: jsonpath returned empty list: .data.url",
  "stacktrace": "github.com/vmware-tanzu/cartographer/pkg/controllers.(*WorkloadReconciler).Reconcile\n\tgithub.com/vmware-tanzu/cartographer/pkg/controllers/workload_reconciler.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"
}
{
  "level": "info",
  "ts": 1655929844.6110914,
  "logger": "tracker-workload",
  "msg": "tracking resource",
  "ref": "ServiceAccount/default/default",
  "obj": "default/workload",
  "ttl": "2022-06-23T16:30:44Z"
}
{
  "level": "info",
  "ts": 1655929844.611112,
  "logger": "tracker-workload",
  "msg": "tracking resource",
  "ref": "ClusterSourceTemplate.carto.run//template",
  "obj": "default/workload",
  "ttl": "2022-06-23T16:30:44Z"
}
{
  "level": "info",
  "ts": 1655929844.611119,
  "logger": "tracker-workload",
  "msg": "tracking resource",
  "ref": "ClusterSourceTemplate.carto.run//template",
  "obj": "default/workload",
  "ttl": "2022-06-23T16:30:44Z"
}
{
  "level": "info",
  "ts": 1655929844.611145,
  "msg": "handled error reconciling workload",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": "default/workload",
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad",
  "supply chain": "test",
  "handled error": "unable to retrieve outputs [.data.url] from stamped object [default/first] of type [configmap] for resource [first] in supply chain [test]: failed to evaluate json path '.data.url': failed to evaluate the url path [.data.url]: jsonpath returned empty list: .data.url"
}
{
  "level": "info",
  "ts": 1655929844.6111555,
  "msg": "finished",
  "controller": "runnable",
  "controllerGroup": "carto.run",
  "controllerKind": "Runnable",
  "workload": {
    "name": "workload",
    "namespace": "default"
  },
  "namespace": "default",
  "name": "workload",
  "reconcileID": "3a191942-f0b3-479f-abe1-1b7106d31dad"
}
</pre>
</details>

### Versions:

- latest `main` (9ba911bdac1ec8495fd6b8d0869b12bec60f348b)

### Deployment info:

local deployment (`./hack/setup.sh cluster cartographer`)

**Comment by squeedee** [comment]
This scenario only occurs if the template was malformed such that it doesn't depend on any inputs specified.
As a supply chain author, you could easily provide inputs that are of no use for the template, but I'm not sure that's a reason to avoid stamping the perfectly valid template.

If you made your second template above use a value from the template context then it would not stamp, you would see a json path error instead.

eg:

```
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: second-template
spec:
  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: $(workload.name)$
    data: 
      url: $(source.url)$
```

**Comment by squeedee** [comment]
If not for YTT i would evaluate the use of template interpolations and warn supply chain authors that their supply chain is over-providing values to the template.

**Comment by squeedee** [comment]
Take a look at the above PR for details.

**Comment by cirocosta** [comment]
thanks @squeedee ! /wont-fix indeed 👍 

> _If you made your second template above use a value from the template context then it would not stamp, you would see a json path error instead._

right! with `ytt` I believe the closest one can do for achieving some similar behavior (guarding against a `nil` | `""` being taken) would be something like

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterDeploymentTemplate
metadata:
  name: second
spec:
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:assert", "assert")
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: #@ "second-" + data.values.workload.metadata.name
    data:
      #@ data.values.deployment.url or assert.fail("missing deployment url")
      url: #@ data.values.deployment.url
```

which can actually provide an error back that points at what's missing:

```yaml
    - conditions:
      - lastTransitionTime: "2022-06-23T18:02:20Z"
        message: "unable to stamp object for resource [second] in supply chain [test]:
          unable to apply ytt template: ytt: Error: \n- assert.fail: fail: missing
          deployment url\n    in <toplevel>\n      stdin.yml:9 |   #@ data.values.deployment.url
          or assert.fail(\"missing deployment url\")\n"
        reason: TemplateStampFailure
        status: "False"
        type: ResourceSubmitted
      - lastTransitionTime: "2022-06-23T18:02:20Z"
        message: ""
        reason: OutputNotAvailable
        status: Unknown
        type: Healthy
      - lastTransitionTime: "2022-06-23T18:02:20Z"
        message: "unable to stamp object for resource [second] in supply chain [test]:
          unable to apply ytt template: ytt: Error: \n- assert.fail: fail: missing
          deployment url\n    in <toplevel>\n      stdin.yml:9 |   #@ data.values.deployment.url
          or assert.fail(\"missing deployment url\")\n"
        reason: TemplateStampFailure
        status: "False"
        type: Ready
```
