### ISSUE TITLE
Debug/track execution of resources in a Supply Chain or a Delivery

### ISSUE THREAD

**Issue by ilozano2** [vmware-tanzu/cartographer#910]
### Description of problem

**Scenario**

Giving a ClusterDelivery composed of several resources/steps
And one resource which has some problem for executing it (example: a ClusterTask that expects some input not provided by a Runnable)
if I create a workload and a delivery pipeline is executed it could fail

**Problem** 
If the workload fails, I can only check workload statuses and logs to figure out what the problem is.

**Example**

`ClusterDelivery`

```
apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: api-delivery
spec:
  selector:
    app.tanzu.vmware.com/deliverable-type: web
    app.tanzu.vmware.com/register-api: "true"

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: delivery-source-template
      params:
        - name: serviceAccount
          value: default # #@ data.values.service_account
        - name: gitImplementation
          value: go-git # #@ data.values.git_implementation

    - name: deployer
      templateRef:
        kind: ClusterDeploymentTemplate
        name: app-deploy
      params:
        - name: serviceAccount
          value: default # #@ data.values.service_account
      deployment:
        resource: source-provider

    - name: register-api
      templateRef:
        kind: ClusterTemplate
        name: api-entity-template
      sources:
        - resource: deployer
          name: deployer
      params:
        - name: serviceAccount
          value: default # #@ data.values.service_account
```

Issue on status section of my workload

> unable to apply ytt template: ytt: Error: 
> - struct has no .annotations field or method (did you mean .generation?)
>     in annotation
>       stdin.yml:14 | #@   if not key in data.values.workload.metadata.annotations:

It would be nice having a way to enable some debug for checking content or state of resources before being executed and after it. Also, I cannot see `stdin.yml` file. Is `stdin.yml` the result of combining ClusterTask + Runnable? How can I check this file for example?

### Proposed solution

TBC

```gherkin
Given a Delivery with a issue in one of their steps/resources 
When a workload that matches with the Delivery is created
and the execution produces an undesired result (error or unexpected outcome)
Then I can re-create the workload with some option that allows me to debug the application
Then I can compare resources before and after they are executed
```

### Example

N/A

## Additional Context

N/A
