### ISSUE TITLE
Cartographer stamps RunTemplates continuously when referenced by multiple Runnables

### ISSUE THREAD

**Issue by idoru** [vmware-tanzu/cartographer#930]
When a RunTemplate is referenced by multiple Runnables, Cartographer will endlessly stamp the template alternately for each Runnable.

Reproduce with the following (courtesy of @waciumawanjohi):
```
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: passing-cluster-task
spec:
  description: |-
    A task that passes
  steps:
    - name: solo-step
      image: busybox
      script: |
        exit 0

---
apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: passing-template
spec:
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: passing-
    spec:
      taskRef:
        name: passing-cluster-task
        kind: ClusterTask


---
apiVersion: carto.run/v1alpha1
kind: Runnable
metadata:
  name: passing
spec:
  runTemplateRef:
    name: passing-template

---
apiVersion: carto.run/v1alpha1
kind: Runnable
metadata:
  name: passing-2
spec:
  runTemplateRef:
    name: passing-template
```
