### ISSUE TITLE
Inconsistent duration marshalling invalidates use of cache

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#95]
### problem

with the introduction of [cache.go], one of the biggest objectives was to ensure that objects like GitRepository (see [GitRepository example]) don't get updated everytime as reconciliations performed by that controller can be quite expensive, but it turns out that depending on how one writes the spec, we can end up observing differences even though they're not meaningful at all.

[cache.go]: https://github.com/vmware-tanzu/cartographer/blob/8e4c7bf903151e703000ab04875f2ee15b31b1f3/pkg/repository/cache.go
[GitRepository example]: https://github.com/vmware-tanzu/cartographer/blob/8e4c7bf903151e703000ab04875f2ee15b31b1f3/experiments/pipeline-service/examples/06-supply-chain-configmap/app-operator/supply-chain-templates.yaml#L24-L33

for instance, using the example where we have the following `ClusterSourceTemplate`:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: git-repository-no-credentials
spec:
  urlPath: .status.artifact.url
  revisionPath: .status.artifact.revision

  template:
    apiVersion: source.toolkit.fluxcd.io/v1beta1
    kind: GitRepository
    metadata:
      name: $(workload.metadata.name)$
    spec:
      interval: 1m                # <<<< 1m, not 1m0s
      gitImplementation: libgit2
      ignore: ""
      url: $(workload.spec.source.git.url)$
      ref: $(workload.spec.source.git.ref)$
```

we can observe that with the current code at 8e4c7bf903151e703000ab04875f2ee15b31b1f3, the cacher always believes there's a diff because .. indeed, a string (marshalled representation of the `time.Duration`) is different:

```
----EXISTING----
(map[string]interface {}) (len=6) {
 (string) (len=17) "gitImplementation": (string) (len=7) "libgit2",
 (string) (len=6) "ignore": (string) "",
 (string) (len=8) "interval": (string) (len=4) "1m0s",                                       <<    !!
 (string) (len=3) "ref": (map[string]interface {}) (len=1) {
  (string) (len=6) "branch": (string) (len=4) "main"
 },
 (string) (len=7) "timeout": (string) (len=3) "20s",
 (string) (len=3) "url": (string) (len=39) "https://github.com/kontinue/hello-world"
}
----END EXISTING----
++++PERSISTED++++
(map[string]interface {}) (len=6) {
 (string) (len=3) "ref": (map[string]interface {}) (len=1) {
  (string) (len=6) "branch": (string) (len=4) "main"
 },
 (string) (len=7) "timeout": (string) (len=3) "20s",                                       <<    !!
 (string) (len=3) "url": (string) (len=39) "https://github.com/kontinue/hello-world",
 (string) (len=17) "gitImplementation": (string) (len=7) "libgit2",
 (string) (len=6) "ignore": (string) "",
 (string) (len=8) "interval": (string) (len=2) "1m"
}
++++END PERSISTED++++
```

to reproduce:

1. apply the following patch

```diff
--- a/pkg/repository/cache.go
+++ b/pkg/repository/cache.go
@@ -19,6 +19,7 @@ import (
        "reflect"
        "time"

+       "github.com/davecgh/go-spew/spew"
        "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
 )

@@ -71,6 +72,7 @@ func (c *cache) UnchangedSinceCached(submitted, existing *unstructured.Unstructu
        submittedKey := getKey(submitted, submittedCachePrefix)
        persistedKey := getKey(submitted, persistedCachePrefix)
        submittedCached, ok := c.ec.Get(submittedKey)
        submittedUnchanged := ok && reflect.DeepEqual(submittedCached, *submitted)

        persistedCached := c.getPersistedCached(persistedKey)
@@ -89,6 +91,14 @@ func (c *cache) UnchangedSinceCached(submitted, existing *unstructured.Unstructu
                return false
        }

+       fmt.Println("----EXISTING----")
+       spew.Dump(existingSpec)
+       fmt.Println("----END EXISTING----")
+
+       fmt.Println("++++PERSISTED++++")
+       spew.Dump(persistedCachedSpec)
+       fmt.Println("++++END PERSISTED++++")
+
        return reflect.DeepEqual(existingSpec, persistedCachedSpec)
 }
```

2. run the `e2e.sh` script (`./hack/ci/e2e.sh`)

3. observe that the generation and observedGeneration fields keep going up as we're constantly patching the object

**Comment by cirocosta** [comment]
the specific example above (`source-controller/GitRepository`) is one where "things change under the hood asynchronously".

it's not that there's a mutating webhook or some form of default'ing via schema that's forcing some values to be set - we're the changes occur at the moment that source-controller's GitRepository reconciler issues a full object `Update()`, for instance, when it adds its finalizer:

https://github.com/fluxcd/source-controller/blob/d7afc3596bdfc3818ed8987db029bea8a461c62c/controllers/gitrepository_controller.go#L105-L108

```go
func (r *GitRepositoryReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {

	// ...

	if !controllerutil.ContainsFinalizer(&repository, sourcev1.SourceFinalizer) {
		controllerutil.AddFinalizer(&repository, sourcev1.SourceFinalizer)
		if err := r.Update(ctx, &repository); err != nil {
			log.Error(err, "unable to register finalizer")
			return ctrl.Result{}, err
		}
	}
```

because at that point its own unmarshaller converted the string to `time.Duration` and then the update marshalls to the proper `time.Duration` format (including seconds), the change happens and then we get into patching on our side.

**Comment by cirocosta** [comment]
looking at the source code again .. it's a little strange that there are no other full object updates - just the initial one to add the finalizer. I wonder if we're missing invalidating the cache in our side 🤔

**Comment by emmjohnson** [comment]
We ran into a similar issue here -

```
---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: deploy-template
spec:
  #@yaml/text-templated-strings
  ytt: |
    #@ load("@ytt:data", "data")

    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: #@ data.values.workload.metadata.name
    spec:
      serviceAccountName: (@= data.values.service_account @)
      noopDelete: false
      fetch:
        - inline:
            paths:
              config.yml: |
                ---
                apiVersion: kapp.k14s.io/v1alpha1
                kind: Config
                rebaseRules:
                  - path: [metadata, annotations, serving.knative.dev/creator]
                    type: copy
                    sources: [new, existing]
                    resourceMatchers: &matchers
                      - apiVersionKindMatcher: {apiVersion: serving.knative.dev/v1, kind: Service}
                  - path: [metadata, annotations, serving.knative.dev/lastModifier]
                    type: copy
                    sources: [new, existing]
                    resourceMatchers: *matchers
        - inline:
            pathsFrom:
            - configMapRef:
                name: #@ data.values.workload.metadata.name
      template:
        - ytt: {}
      deploy:
        - kapp: {}
```

The noopDelete field is getting omitted after kapp controller does an update for the finalizers. Our persistent spec cache check is then failing because our persistent cache has noopDelete as false but when we go check the server it is omitted.  

Unsure the correct path forward here.
