### ISSUE TITLE
Support params specific to template option selected

### ISSUE THREAD

**Issue by xyloman** [vmware-tanzu/cartographer#974]
### Description of problem

Ability to have specific parameters passed to a template when selected via options: 

### Proposed solution

Update options selection of the templateRef for a resource to take option specific params.

```gherkin
Given a templateRef with options
When parameters need to flex based upon the selected template
Then parameters specific to the selected template will be provided
```

### Example

```
  - name: image-provider
    templateRef:
      kind: ClusterImageTemplate
      options:
        - name: kpack-template
          selector:
            matchFields:
              - key: spec.params[?(@.name=="dockerfile")]
                operator: DoesNotExist
              - key: spec.image
                operator: DoesNotExist
           params:
              - name: clusterBuilder
                default: #@ data.values.cluster_builder
              - name: serviceAccount
                value: kpack-image-builder-service-account
              - name: registry
                value: myregistry2.com/myrepo
        - name: kaniko-template
          selector:
            matchFields:
              - key: spec.params[?(@.name=="dockerfile")]
                operator: Exists
              - key: spec.image
                operator: DoesNotExist
          params:
              - name: dockerfile
                default: ./Dockerfile
              - name: docker_build_context
                default: ./
              - name: docker_build_extra_args
                default: []
              - name: serviceAccount
                value: docker-image-builder-service-account
              - name: registry
                value: myregistry.com/myrepo
        - name: image-provider-template
          selector:
            matchFields:
              - key: spec.image
                operator: Exists
    sources:
    - resource: source-git
      name: source
```
