### ISSUE TITLE
healthrules: messagePath is treated as a requirement

### ISSUE THREAD

**Issue by cirocosta** [vmware-tanzu/cartographer#983]
### Bug description:

in the rfc that introduced `healthRules` (see [readable version of the RFC](https://github.com/vmware-tanzu/cartographer/blob/rfc-resources-report-status/rfc/rfc-0000-allow-resources-to-report-status.md)) it's stated:

> _Authors can also optionally define a messagePath, which is a path in the resource where Cartographer can pull off a message to display in the owner status._

however, absent of such field, we always end up with a message that indicates that an error occurred, which gives the impression that such field is treated as a requirement.

for instance, consider the following supply chain:

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: app
spec:
  selector:
    foo: bar

  resources:
    - name: first
      templateRef:
        kind: ClusterImageTemplate
        name: template
```

with the template being defined as

```yaml
apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: template
spec:
  params:
    - name: healthy
      default: "yep"

  imagePath: .data.image

  healthRule:
    multiMatch:
      healthy:
        matchFields:
          - key: 'data.healthy'
            operator: 'In'
            values: ['yep']
      unhealthy:
        matchFields:
          - key: 'data.healthy'
            operator: 'NotIn'
            values: ['yep']

  template:
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: $(workload.metadata.name)$
    data:
      image: foo
      healthy: $(params.healthy)$
```

now, creating a workload that matches the supply chain, we end up with:

```yaml
kind: Workload
status:
  conditions:
  - reason: Ready
    status: "True"
    type: SupplyChainReady
  - reason: ResourceSubmissionComplete
    status: "True"
    type: ResourcesSubmitted
  - reason: HealthyConditionRule
    status: "True"
    type: ResourcesHealthy
  - reason: Ready                            #! yep, we're ready
    status: "True"
    type: Ready
  observedGeneration: 1
  resources:
  - name: first
    conditions:
    - reason: ResourceSubmissionComplete
      status: "True"
      type: ResourceSubmitted
    - reason: MatchedField
      status: "True"                        #! yep, we're healthy
      message: 'field value: yep, message: unknown, error retrieving message path []'
      type: Healthy                         #!        '---.
    - reason: Ready                         #!          "error" implying requirement
      status: "True"
      type: Ready
```

### Steps to reproduce:
Please provide a set of steps to reproduce the behavior (example):
1. apply the objects above
2. observe status of Workload

### Expected behavior:

keep being `ready: true` as we see, but, in the `message` field for the resource condition (type healthy), avoid mentioning the lack of `messagePath` as an error (in case `messagePath` points at something that's indeed wrong, I think it makes sense to explicitly mention that it's indeed an error but then also `ready: false` it).

### Versions:
 - local kind cluster (1.23.4)
 - cartographer version (latest main - b5a7d29f43ffa5054cf164bb30985f290e5083aa)
 - k8s version (1.23.4)

### Additional context:

see https://github.com/vmware-tanzu/cartographer/blob/2ee79e68041b06c62d2326673fb2376a0b22e380/pkg/realizer/healthcheck/healthcheck.go#L122-L125
